/**
 * @file demo_screen.c
 * Pre-MVP demo screen: basic shapes, text, an image, and a touch target.
 *
 * Laid out for the wide-short 1920x440 panel: shapes on the left, the image
 * in the centre, and the title + touch target on the right.
 */
#include "demo_screen.h"

#include <stdio.h>

#include "lvgl.h"

/* Generated by scripts/gen-image.sh from assets/brain_rot.png via
 * lib/lvgl/scripts/LVGLImage.py. Symbol name follows the output file basename. */
extern const lv_image_dsc_t brain_rot;

static lv_obj_t *s_coord_label;
static lv_obj_t *s_touch_btn;
static uint32_t s_tap_count;

static void touch_event_cb(lv_event_t *e) {
    (void)e;
    s_tap_count++;

    /* Visible feedback: cycle the button colour on each tap. */
    static const uint32_t palette[] = {0x2e7d32, 0xc62828, 0x1565c0, 0xf9a825};
    lv_color_t c = lv_color_hex(palette[s_tap_count % 4]);
    lv_obj_set_style_bg_color(s_touch_btn, c, LV_PART_MAIN);

    /* Report the tap coordinates from the active input device. */
    lv_indev_t *indev = lv_indev_active();
    lv_point_t p = {0, 0};
    if (indev)
        lv_indev_get_point(indev, &p);
    lv_label_set_text_fmt(s_coord_label, "tap #%u  @ %d,%d",
                          (unsigned)s_tap_count, (int)p.x, (int)p.y);
}

void demo_screen_create(void) {
    lv_obj_t *scr = lv_screen_active();
    lv_obj_set_style_bg_color(scr, lv_color_hex(0x101418), LV_PART_MAIN);
    lv_obj_clear_flag(scr, LV_OBJ_FLAG_SCROLLABLE);

    /* ---- Left zone: shapes (rectangle, circle, line) ---- */

    /* Rectangle */
    lv_obj_t *rect = lv_obj_create(scr);
    lv_obj_set_size(rect, 180, 120);
    lv_obj_set_pos(rect, 40, 60);
    lv_obj_set_style_radius(rect, 8, LV_PART_MAIN);
    lv_obj_set_style_bg_color(rect, lv_color_hex(0x3949ab), LV_PART_MAIN);
    lv_obj_set_style_border_width(rect, 0, LV_PART_MAIN);
    lv_obj_clear_flag(rect, LV_OBJ_FLAG_SCROLLABLE);

    /* Circle (object with full-radius corners) */
    lv_obj_t *circle = lv_obj_create(scr);
    lv_obj_set_size(circle, 140, 140);
    lv_obj_set_pos(circle, 60, 230);
    lv_obj_set_style_radius(circle, LV_RADIUS_CIRCLE, LV_PART_MAIN);
    lv_obj_set_style_bg_color(circle, lv_color_hex(0x00897b), LV_PART_MAIN);
    lv_obj_set_style_border_width(circle, 0, LV_PART_MAIN);
    lv_obj_clear_flag(circle, LV_OBJ_FLAG_SCROLLABLE);

    /* Line */
    static lv_point_precise_t line_pts[] = {{280, 80}, {460, 200}, {280, 340}};
    lv_obj_t *line = lv_line_create(scr);
    lv_line_set_points(line, line_pts, 3);
    lv_obj_set_style_line_width(line, 6, LV_PART_MAIN);
    lv_obj_set_style_line_color(line, lv_color_hex(0xfdd835), LV_PART_MAIN);
    lv_obj_set_style_line_rounded(line, true, LV_PART_MAIN);

    /* ---- Centre zone: image ---- */
    lv_obj_t *img = lv_image_create(scr);
    lv_image_set_src(img, &brain_rot);
    lv_obj_align(img, LV_ALIGN_CENTER, 0, 0);

    /* ---- Right zone: title, touch target, coordinate readout ---- */
    lv_obj_t *title = lv_label_create(scr);
    lv_label_set_text(title, "kdeskdash pre-MVP");
    lv_obj_set_style_text_font(title, &lv_font_montserrat_28, LV_PART_MAIN);
    lv_obj_set_style_text_color(title, lv_color_hex(0xeceff1), LV_PART_MAIN);
    lv_obj_set_pos(title, 1300, 60);

    s_touch_btn = lv_button_create(scr);
    lv_obj_set_size(s_touch_btn, 360, 140);
    lv_obj_set_pos(s_touch_btn, 1300, 130);
    lv_obj_set_style_bg_color(s_touch_btn, lv_color_hex(0x2e7d32), LV_PART_MAIN);
    lv_obj_add_event_cb(s_touch_btn, touch_event_cb, LV_EVENT_CLICKED, NULL);

    lv_obj_t *btn_label = lv_label_create(s_touch_btn);
    lv_label_set_text(btn_label, "Touch me");
    lv_obj_set_style_text_font(btn_label, &lv_font_montserrat_28, LV_PART_MAIN);
    lv_obj_center(btn_label);

    s_coord_label = lv_label_create(scr);
    lv_label_set_text(s_coord_label, "waiting for touch...");
    lv_obj_set_style_text_font(s_coord_label, &lv_font_montserrat_20, LV_PART_MAIN);
    lv_obj_set_style_text_color(s_coord_label, lv_color_hex(0xb0bec5), LV_PART_MAIN);
    lv_obj_set_pos(s_coord_label, 1300, 300);
}
